### ISSUE TITLE
fatal error: qmkl/raspberrypi-firmware.h: No such file or directory

### ISSUE THREAD

**Issue by czy2014hust** [Idein/qmkl#50]
When I compile the qmkl, there is not a file named "raspberry-firware.h" under the qmkl folder.How can I get the file?Thank you.

**Comment by Terminus-IMRC** [comment]
We're sorry. Fixed it in the latest commit. Please make sure that the build passes.

**Comment by czy2014hust** [comment]
Thank you！👍
