### ISSUE TITLE
Failed to run test/scopy and test/vsAbs

### ISSUE THREAD

**Issue by ailihong** [Idein/qmkl#52]
hello,every one
      Thank you very much for the excellent work of the author.I succeed running test/sgemm,output as beblow:
./test/sgemm 
P = 96
Q = 363
R = 3072
ALPHA = 1.000000
BETA = 1.000000
==== sgemm example (ALPHA * 96x363 * 363x3072 + BETA * 96x3072) ====
GPU: 0.022416 [s], 9.59096e+09 [flop/s]
CPU (4 threads): 4.83363 [s], 4.44781e+07 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 0.000930786
Minimum relative error: 0
Maximum relative error: 0.609868

but i fail test/scopy and test/vsAbs,program gives some error as below:
usrvcsm: [vcsm_malloc_cache]: [3751] [rpimemmgr]: ioctl mem-alloc FAILED [-1] (hdl: 0)
/home/pi/bai/librpimemmgr/src/vcsm.c:30:alloc_mem_vcsm: error: Failed to allocate memory with VCSM
/home/pi/bai/qmkl/src/memory.c:51: Failed to allocate memory with rpimemmgr

i donnot kown why.i use raspberry pi zero with Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux.
Thank you very much for any suggestions.

**Comment by Terminus-IMRC** [comment]
Thank you for using our library.  scopy and vsAbs tests consume more memory than others, so please run `sudo raspi-config` and increase the size of GPU memory.  You may refer to:
- https://www.raspberrypi.org/documentation/configuration/raspi-config.md
- https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md

**Comment by ailihong** [comment]
Got it.Thank you very much.
